# Generated by Django 3.1 on 2021-01-12 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='subject',
            new_name='message',
        ),
    ]
