# Generated by Django 3.1.4 on 2021-01-01 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_post_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
