# Generated by Django 3.1 on 2021-01-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210112_1123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.TextField(default=True),
        ),
    ]
